{{ define "header" }}
{{- $tags := tags -}}
{{- $inject := inject -}}
{{- if $tags -}}
//go:build{{ range $tags }} {{ . }}{{ end }}

{{ end -}}
{{- if first -}}
// Package {{ pkg }} contains generated code for schema '{{ schema }}'.
{{ end -}}
package {{ pkg }}

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"encoding/csv"
	"errors"
	"fmt"
	"io"
	"os"
	"regexp"
	"strings"
	"time"
	"net"
{{- if driver "postgres" }}
	_ "github.com/jackc/pgx/v5/stdlib" // pgx postgres driver
	pgtype "github.com/jackc/pgx/v5/pgtype"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	pgx "github.com/jackc/pgx/v5"
	"github.com/samber/lo"
{{ end }}{{ range imports }}
	{{ with .Alias }}{{ . }} {{ end }}{{ .Pkg }}
{{ end }}
)

{{- if $inject }}
{{ $inject }}
{{- end }}
{{ end }}
